### ISSUE TITLE
Custom Pop-up is cut off by scroll bar, add padding to top of pod 

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/configurable-locator#164]
When a custom pop-up is configured in the application it doesn't display clearly. 

Please update the popup and pod containing the custom popup information to display more clearly. 
- [x] Add space at the top of popup\pod so the itext isn't so close to the icon
- [x] Ensure text isn't cut off by the custom scroll bar. 

Images illustrate the issue below:

![screen shot 2015-06-03 at 1 55 26 pm](https://cloud.githubusercontent.com/assets/2379312/7967491/605c3c00-09f8-11e5-8534-76ebce4240e0.png)
![screen shot 2015-06-03 at 1 55 50 pm](https://cloud.githubusercontent.com/assets/2379312/7967500/693b1efe-09f8-11e5-8376-ec5e97d43cdf.png)

**Comment by lindsayking** [comment]
@LindsayThomas 

This behavior is much better in v1.5.  Examples below using the [water access app](http://50.18.115.76/WaterAccessLocatorSG1.5/), which has been configured with a custom popup.

Pod in popup window:
![image](https://cloud.githubusercontent.com/assets/4316336/8936322/5d07d95e-3506-11e5-9302-ac6d384f9f01.png)



Pod in bottom panel:
![image](https://cloud.githubusercontent.com/assets/4316336/8936334/71f303e8-3506-11e5-9c6c-02878a73d8ba.png)

**Comment by LindsayThomas** [comment]
trails
