### ISSUE TITLE
Unchecking the parameter for "Turn On 1000 separator" on a webmap causes the application to freeze

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/configurable-locator#167]
Configure the Locator Application with the data structure for Facilities using this structure
Data Structure is here Parks10000.mpk: https://esri.box.com/s/697rqhctosb8cb41k4wnayabxu8suojy

-Publish the service
-Create a AGOL WebMap
-Configure the Popup for Parks
-Run the application (will work as expected) 

-Go into the map and reconfigure the pop-up 
-In the Pop-up find the Field "Number of Parking Spots"
-Configure the field to have 0 decimals 
-uncheck the box for "Turn On 1000 separator"
-run the application search, the application will freeze up

![uncheck](https://cloud.githubusercontent.com/assets/2379312/8036827/32564520-0dc8-11e5-8231-b4a9185f413f.png)

**Comment by lindsayking** [comment]
@LindsayThomas 

After configuring the popup in http://50.18.115.76/WaterAccessLocatorSG1.5/ to have the Number of Parking Spaces attribute turned on, with no decimal places or comma seperator, the application continues to work as expected.

However, the Number of Parking spaces field is blank for all records.  The box link to the mpk you referenced above does not appear to be active, so I am unable to confirm the app would work if the field is populated with values.

**Comment by lindsayking** [comment]
Using webmap id:fd598d1fcf5142f69e65b83093d22a22, which has the Number of Parking Spaces field populated with values, we could confirm that the app continues to function as expected even after the 
* number of parking spaces field is turned on in the popup configuration
* the field is configured with 0 decimal places
* the field is configured with the comma separator turned off

**Comment by MikeTschudi** [comment]
V1.5 does not fix the source of the error; see branch https://github.com/Esri/configurable-locator/tree/infoWindow_number_fix for a fix

**Comment by CTLocalGovTeam** [comment]
@MikeTschudi 

We saw the branch and found that the same fix is submitted in the pull request for v1.5

Here is a snip of the diff at infowindowHelper.js and myList.js
![image](https://cloud.githubusercontent.com/assets/2959186/9131844/d60b5804-3d0c-11e5-9739-da408b3254aa.png)

![image](https://cloud.githubusercontent.com/assets/2959186/9131877/2c9a9cac-3d0d-11e5-8af7-25e87f788803.png)



Please let us know if we are missing something.

**Comment by MikeTschudi** [comment]
@CTLocalGovTeam, thanks for pointing it out!
