### ISSUE TITLE
Event Search Expression update

### ISSUE THREAD

**Issue by lindsayking** [Esri/configurable-locator#174]
We need to modify the SearchExpression under <code>EventSearchSettings</code> to allow users to search both by event type and by event name.  

FYI @LindsayThomas

**Comment by LindsayThomas** [comment]
- [ ] Event Calendar
- [ ] Events Locator

**Comment by lindsayking** [comment]
@LindsayThomas  Updated configEventLocator.js for State Gov.

**Comment by LindsayThomas** [comment]
@lindsayking did we test if this is affected by the AGOL security setting issue we had for the other search expression?

**Comment by lindsayking** [comment]
@LindsayThomas   

Tested with the "Allow only SQL queries" security setting in the org both checked and unchecked.  Search results were not affected by the org setting.

**Comment by LindsayThomas** [comment]
LG commit - https://github.com/Esri/configurable-locator/commit/6e4bee76f1211bc561cfd87a680c6ed76c557201
