### ISSUE TITLE
On phone devices the popup header displays as "N/A" when : is not present

### ISSUE THREAD

**Issue by lindsayking** [Esri/configurable-locator#175]
@CTLocalGovTeam 

The popup header has a colon ( : ) requirement. 
If the popup header does not have a : then on phones when you tap on a feature  "N/A" is displayed.

Pleases display the pop header configured by the user. (thus removing the : requirement) 

@LindsayThomas

**Comment by lindsayking** [comment]
@LindsayThomas   Tested this using http://50.18.115.76/EventLocatorSG1.5/ on android phone and iPhone6.  Popup is showing the placename, no longer N/A.

**Comment by LindsayThomas** [comment]
lg
