### ISSUE TITLE
When mobile popup window is present collapse menu when user clicks on name of event

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/configurable-locator#176]
Repro Steps:
Go to http://tryitlive.arcgis.com/eventscalendar/  (View on a phone)
Search > Date  
Populate From Date (current date) and To Date ( 9/30/2015) > Click Search
Click on the "Naperville Wine Festival" that is displayed in the Date\Event list
Map will zoom to the feature but he feature is underneath the menu and not visible by the user

Please update the application to collapse the search menu when a feature is selected when the mobile popup window (the little popup) is present. This should not collapse when the full size pop up is present, because that means there is usually enough map to see the feature) 

Note: Issue is present in the configurations for Events Locator \ Events Calendar (configEventsCalendar.js \ configEventLocator.js)

**Comment by lindsayking** [comment]
Verified with http://50.18.115.76/EventLocatorSG1.5/ on Android phone and iPhone 6.
