### ISSUE TITLE
Update application to clearly show the nearest feature, buffer, route.  (zooms to close to the route now.) 

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/configurable-locator#179]
Repro Steps
On a desktop browser 
Go to http://tryitlive.arcgis.com/parklocatorLG/
Search > Location\Park\Activity
Application will route to the nearest feature fitting the search criteria.

Please update the application to show the results of the search criteria with the buffer, route and feature clearly visible (Much like the old park finder application)

**Comment by lindsayking** [comment]
@LindsayThomas 

Using the [water access locator](http://50.18.115.76/WaterAccessLocatorSG1.5/) as an example:

Searching by location
* No longer zooms to the route; it zooms to the buffer
* All search results matching search criteria display
* Route displays

However, the buffer is partially obscured by the bottom panel.
![image](https://cloud.githubusercontent.com/assets/4316336/8934850/8148e2fc-34fe-11e5-967b-6e40f7766ca8.png)


Searching by activity
* Zooms to the extent of the route
* All search results matching search criteria display

However, the route is also partially obscured by the bottom panel.
![image](https://cloud.githubusercontent.com/assets/4316336/8934889/b91c09b6-34fe-11e5-85fc-5a49242c0c39.png)

**Comment by LindsayThomas** [comment]
When buffer is present (location) app zooms to it, and draws nearest route (zoom is at buffer). User can then select another route and it will zoom to it. 

Searching for a "park" will zoom to a park. But will not zoom in. It will remain at the same zoom level the application is currently at. 

Searching for amenities will use geolocation, and buffer is not present. Will zoom to route.
