### ISSUE TITLE
Smartphones only shows one option when searching for amenities \ parks

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/configurable-locator#182]
Update Smartphones to shows all results instead of just one option when searching for amenities \ parks

Phone\ Mobile  mobile sized browser workflows

Mobile workflow 1 -Repro Steps
On a phone or mobile sized browser 
Go to http://tryitlive.arcgis.com/parklocatorLG/
Search > Activity > Select "Restrooms" > Go
Application will route to the nearest park with that activity
User will not see the list of all Features(parks) that have the Activity "Restrooms". 

Please update the application to display all the results of the search

Mobile workflow 2 -Repro Steps
On a phone or mobile sized browser 
Go to http://tryitlive.arcgis.com/parklocatorLG/
Search > for a location > select an address
Application will route to the nearest park 
User will not see the list of all Features(parks) available 

Please update the application to display all the results of the search

![screen shot 2015-07-07 at 2 39 22 pm](https://cloud.githubusercontent.com/assets/2379312/8554172/2c193c12-24b6-11e5-9483-d60962ec56ff.png)

**Comment by CTLocalGovTeam** [comment]
@LindsayThomas 

To display the list of results on smartphones, we are thinking of an approach that minimizes the functional difference between desktop and mobile modes.
On desktops, we zoom to buffer and auto-route to nearest facility. Hence, on mobiles too, we should zoom to buffer and auto-route to nearest. 
This also minimizes device dependent functional code that we write.

We request an early approval/comment on this approach. This will help us to derive the delivery date.

When user clicks an address:
* zoom to buffer, auto-route to nearest
* display the list of results (screen 1)
* user can select a different facility, this will regenerate the route
  * should we zoom to route when a different facility/result is selected, when route is regenerated?
* user can minimize the list of results using the button (screen 2)
* auto-minimize the results list when search window is opened again
  * if a search is performed, close search window and re-open the list with new results

![image](https://cloud.githubusercontent.com/assets/2959186/8725346/54e6b0a6-2bf1-11e5-9948-97061ebc0491.png)

**Comment by LindsayThomas** [comment]
@CTLocalGovTeam Please implement. Note the one clarification below

CT says "user can select a different facility, this will regenerate the route
should we zoom to route when a different facility/result is selected, when route is regenerated?"

Esri says: Yes, if the user selects another feature then pleas zoom to route when a different facility/result is selected. Also, minimize the panel when this happens.

**Comment by lindsayking** [comment]
@LindsayThomas 

This has been tested using http://50.18.115.76/EventLocatorSG1.5/, http://50.18.115.76/ParkLocatorSG1.5/ and http://50.18.115.76/WMALocatorSG1.5/ on an Android phone and iPhone 6.  The application routes to the nearest feature and the bottom panel displays with a list of features that match the search criteria.  When a different result is selected from the bottom panel, the panel automatically minimizes and the application zooms to the extent of the route to the selected feature.

This is the behavior for both address search and amenities/activiy search.

**Comment by LindsayThomas** [comment]
iphone 6 events (zoom to buffer first, then select route and go route extent, minimize happens.)
