### ISSUE TITLE
Uncaught TypeError when window resized after app startup

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/configurable-locator#187]
Run the try-it-live version (http://tryitlive.arcgis.com/ParkLocatorLG/), open the debugging console, and resize the browser window.  You'll get the following error with each change:

```
Uncaught TypeError: Cannot read property 'nodeType' of null
```

This is caused by internal references to 'myList' before it is created; it is fixed in branch https://github.com/Esri/configurable-locator/tree/window_resize_fix.  (Reproducible in V1.5 as well.)

**Comment by lindsayking** [comment]
Verified with https://github.com/Esri/configurable-locator/commit/afa8bd0c1df19981ef38730978fb20a41a359f9f
