### ISSUE TITLE
Shelter Locator TIL services,Webmap ID, and basemap group should use TIL ORG and\or Server

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/configurable-locator#191]
Add Shelter Locator TIL services,Webmap ID, and basemap group should use TIL ORG and\or Server

@lindsayking @jessnoo

**Comment by jessnoo** [comment]
These are set up for the configs for Shelter Locator for EM/State - and the config i shared with LK references these.

- Map: http://statelocaltryit.maps.arcgis.com/home/item.html?id=07d02a9e8a2f42b6945fb21cf851a211

- Service: http://statelocaltryit.maps.arcgis.com/home/item.html?id=4e43a84b1c484121b64ea9073c676200 

@LindsayThomas @lindsayking do we need separate TIL AGOL items for State and EM? i was thinking they could probably share the same service and map. i wanted to ask in the case there was a rule about that.

**Comment by LindsayThomas** [comment]
@jessnoo @lindsayking no rule. I think, if it is the exact service then just use it in both applications. Just double tag.

**Comment by jessnoo** [comment]
@lindsayking helped with creating basemap group for EM

webmap and service updated today to use definition queries for separating Open and Closed shelters in the app config.

**Comment by lindsayking** [comment]
Done.
