### ISSUE TITLE
Make "Yes" "No" values configurable items

### ISSUE THREAD

**Issue by lindsayking** [Esri/configurable-locator#194]
The application is currently hardcoded to look for "Yes" or "No" values to indicate whether or not an amenity is present.  But if users have a different domain in place, e.g. "Y" or "N", the app would not recognize these values.  Perhaps we should make this a configurable item in the config.js.

@NikkiGolding @ScottOppmann @LindsayThomas  Thoughts?

**Comment by ScottOppmann** [comment]
@lindsayking - Did this request come from a specific user?  If not, I would be inclined to defer this.

**Comment by lindsayking** [comment]
@ScottOppmann It came from Kevin (Solutions Engineer) working with a dataset from South Carolina.

**Comment by LindsayThomas** [comment]
@ScottOppmann We do not hardocode as a rule meaning this is inconsistent with other applications. I would prefer to put this in the config.js

**Comment by jmhauck** [comment]
Added "QualifyingActivityValue" to the config and updated the additional js files that would need to read the value. As I enter this I have realized that I'll need to update the additional sample configs still.

**Comment by lindsayking** [comment]
Tested with a Y/N domain on a sample dataset.  Configured the app to set <code>QualifyingActivityValue</code> to "Y" rather than "Yes".  App behaved appropriately and search results made sense.
