### ISSUE TITLE
IE10 only: First click not detected when dropping a point on the map

### ISSUE THREAD

**Issue by lindsayking** [Esri/configurable-locator#201]
This behavior appears to be specific to IE10.  Cannot repro in IE9, IE11 or other browsers.  The Drop a Point tool sometimes requires the user to click twice in order get a pin to display and a search to execute.  The repro steps below use Event Calendar as an example, but this behavior is present in all configurations.

Steps to repro:
1.	Launch http://50.18.115.76/EventCalendarDec15 
2.	Get the drop a point tool
3.	Click the map >> search happens
4.	Get the drop a point tool
5.	Click the map >> nothing happens
6.	Click the map again >> search happens
7.	Get the drop a point tool
8.	Click the map >> search happens
9.	Get the drop a point tool
10.	Click the map >> nothing happens
11.	Click the map again >> search happens

**Comment by jmhauck** [comment]
The app currently targets JS API 3.13...the issue that causes this has been resolved in JS API 3.14. Should we upgrade the JS API?

**Comment by lindsayking** [comment]
@jmhauck  I haven't been able to reproduce this behavior with http://50.18.115.76/EventCalendarDec15v5, but I'm going to ask @jessnoo to try as well since she is the one who reported the behavior originally.

**Comment by lindsayking** [comment]
This issue does not appear to be fixed with the upgrade to JS API 3.15 according to @jessnoo

**Comment by lindsayking** [comment]
No action required at this time.
