### ISSUE TITLE
Popups do not share correctly

### ISSUE THREAD

**Issue by lindsayking** [Esri/configurable-locator#202]
When a popup is triggered for any feature that the app is configured against (e.g. an activity or an event), that popup does not display in the shared version of the app.  This behavior has a couple of  consequences:
* Active popup in original app is not present in shared version 
* Any routes calculated from the popup in the original app do not display in the shared version

This is a new issue.  It is not present in the currently-released version.

Note, if a popup is triggered for a feature that is not a configured data source for the application (e.g. Trails in the [Park Locator](http://50.18.115.76/ParkLocatorLGDec15) ), that popup displays correctly in the shared version of the app.  This issue only appears to affect layers that are configured in the applications' config.js.

**Comment by lindsayking** [comment]
Tested with commit https://github.com/Esri/configurable-locator/commit/6a786ff75d0e3405f6293532d64e4ec119c0a9c7

Scenarios tested:
    - Activity popup opened and shared - successful
    - route generated from activity popup and shared - successful
    - overlapping contextual+activity popups activated and shared  (#203) - successful
    - Route generated from popup, but then a different popup opened - UNSUCCESSFUL: Shared app displays with the correct popup intially, but then the map zooms to the extent of the route.  So the extent is slightly different from the original app.  This is a different behavior from the try it lives, which honor the extent of the original app in the shared version.

**Comment by jmhauck** [comment]
This should go away again with the switch back to 3.13...4e671951e54f43f2907391b9d49ce1eb0b85b2cb

**Comment by lindsayking** [comment]
All scenarios listed above pass successfully with https://github.com/Esri/configurable-locator/commit/6df4bd1ae2006002827add9aaae58d9a380d55dc
