### ISSUE TITLE
Discuss adding links to Solutions Site help into help.htms

### ISSUE THREAD

**Issue by lindsayking** [Esri/configurable-locator#205]
@jessnoo suggested adding a link to our respective Solutions Site pages into the help.htm for each app (see image below).  This is doable - particularly using shortlinks - but we need to discuss whether we should for a future release.  Would it be confusing?  Would users expect to be directed to their city/state pages?

![help](https://cloud.githubusercontent.com/assets/4316336/11641641/305274c8-9cee-11e5-92df-f1a4ac5c8d25.png)

**Comment by LindsayThomas** [comment]
@lindsayking  I think we should just remove this completely
