### ISSUE TITLE
Popup should display information for point features before point or polygon features 

### ISSUE THREAD

**Issue by lindsayking** [Esri/configurable-locator#213]
This is not a new issue.  It exists in previous releases.

When point features overlap line (e.g. in [Park Locator](http://50.18.115.76/ParkLocatorLGDec15)) or polygon (e.g. in [WMA Locator](http://50.18.115.76/WMALocatorDec15)) features, the popup displays information for the line or polygon feature(s) first.  The user must click the ">" to progress through the stacked popups to see the popup information for the point feature.

**Comment by jmhauck** [comment]
So we have this documented. Seems like the layers that are configured as a part of the app are what we are after rather than sorting by geometry type but please correct me if I am wrong.

**Comment by lindsayking** [comment]
@jmhauck  Updated URLs for seeing this behavior:  [Park Locator](http://tryitlive.arcgis.com/ParkandRecLocator/) and [WMA Locator](http://tryitlive.arcgis.com/WMALocator/).

**Comment by lindsayking** [comment]
@jmhauck   This looks good now with commit https://github.com/Esri/configurable-locator/commit/c6c444000488b45e281fe04e2d33d0c11b01ab1b.  I'm seeing the popup for points first, then lines and polygons after.  If the map contains all three geometry types, the popups for the features display in the correct order (points, then lines, then polys).
