### ISSUE TITLE
Point config.js and proxy to try it live webmap id and services

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/configurable-locator#223]
Point config.js and proxy to try it live webmap id and services
- [x] config.js removed
- [x] configParkLocator.js renamed to config.js
- [x] proxy file references to dev server removed
- [x] update readme to reflect this

**Comment by lindsayking** [comment]
@LindsayThomas

* All configs are pointing to Try It Live webmaps
* original config.js has been removed
* configParkLocator.js renamed to config.js
* readme updated to reflect config.js change
* no changes needed for proxy.config; there were no references to the dev server
