### ISSUE TITLE
When double-click is used to clear the search panel, subsequent searches produce no results

### ISSUE THREAD

**Issue by lindsayking** [Esri/configurable-locator#229]
Steps to repro:
1) Launch the app and click OK in the splash screen
2) On the search panel, double-click in the search box to clear the default search text
3) Provide new location search in the search box.  Note that no search results are returned.  

This issue may have been introduced with https://github.com/Esri/configurable-locator/commit/afa8bd0c1df19981ef38730978fb20a41a359f9f.

**Comment by NikkiGolding** [comment]
@MikeTschudi  Will you take a look at this?

**Comment by MikeTschudi** [comment]
App was programmed to permanently hide results after a double-click: results were present, but could not be seen

**Comment by lindsayking** [comment]
@MikeTschudi  -  This issue is now fixed.  After using double-click to clear the search panel, subsequent searches successfully return results.

However, with this latest change, double-clicking in the search box on the search panel now clears the search entirely: from the search panel and from the map.
* Double-clicking the search box should clear the text from the search box and any search results on the search panel, but not clear the map or bottom panel.
* Clicking the "X" on the search panel should clear everything: the search panel, the map (ripple, buffer, route, etc) and the bottom panel.

Created https://github.com/Esri/configurable-locator/issues/230 for this new behavior.
