### ISSUE TITLE
Double-clicking in the textbox on the search panel should only clear the search panel

### ISSUE THREAD

**Issue by lindsayking** [Esri/configurable-locator#230]
* Double-clicking the search box should clear the text from the search box and any search results on the search panel, but not clear the map or bottom panel.
* Clicking the "X" on the search panel should clear everything: the search panel, the map (ripple, buffer, route, etc) and the bottom panel.

Currently, double-clicking the search box on the search panel is behaving like clicking the "X".  It is clearing the map and bottom panel in addition to the search panel, when it should only be clearing the search panel.

**Comment by MikeTschudi** [comment]
Adapted from notes from Lindsay K:

Double-clicking in a search text box or clicking the "X" to the right of a search text box clears the search text box contents as well as any search results in the same search panel, whether the search box appears in the dropdown search panel, a feature's popup, or the bottom results panel.

Clicking the "X" to the right of the search text box also clears map buffer graphics, direction graphics, and the bottom panel, but only when it is used in the dropdown search panel.

**Comment by lindsayking** [comment]
Verified with commit https://github.com/Esri/configurable-locator/commit/79552c9404c4294a0639916c75d65cdd298969ab
