### ISSUE TITLE
Directions Buffer

### ISSUE THREAD

**Issue by jbo0225** [Esri/configurable-locator#232]
Hi,
While working with the server and SDK techs at ESRI, they discovered distance=1500 buffer is being used when calculating directions.  In our implementation, this is making the directions to the entrance points to our parks way off from the actual point on the map.  Is there any way to change this?

Thanks,
Josh

**Comment by LindsayThomas** [comment]
@jbo0225 We updated the source code to support adjusting the buffer when a search is executed. 
You can see a change in the "try it live" version of the app here: http://tryitlive.arcgis.com/ParkLocatorLG/

The Buffer Settings are in the config.js, see the example below

`        // BUFFER SETTINGS
        // ------------------------------------------------------------------------------------------------------------------------

        // Set buffer distance unit and limits
        DistanceUnitSettings: {
            DistanceUnitName: "Miles", // Allowed values for DistanceUnitName are "Miles", "Kilometers", "Meters" and "Feet".
            MinimumValue: 1,
            MaximumValue: 50
        },

        // FillSymbolColor: Setting color for buffer in RGB format
        // FillSymbolTransparency: Setting transparency for buffer
        // LineSymbolColor: Setting outline color of buffer in RGB format
        // LineSymbolTransparency: Setting transparency for outline symbol
        BufferSymbology: {
            FillSymbolColor: "0,0,255",
            FillSymbolTransparency: "0.01",
            LineSymbolColor: "0,0,255",
            LineSymbolTransparency: "0.65"`

**Comment by LindsayThomas** [comment]
@lindsayking FYI

**Comment by jbo0225** [comment]
Thanks, we now definitely can see some improvements the accuracy of directions in a few locations where it was clearly way off.  There's still other points that are coming out wrong, but we'd have to consult with tech support to see if there's something just off with the data in the routing service or something with our actual data.
